apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: solax-postgres-db
    access: proxy
    url: db:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: 'disable' # Standard for local docker setups
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500 # Matches our postgres:15 image
      timescaledb: false
